# Generated by Django 3.1.4 on 2021-10-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
