# Generated by Django 3.1.4 on 2021-10-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20211005_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(default=22281, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
