# Generated by Django 3.1.4 on 2021-10-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_category_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='categogy',
            new_name='category',
        ),
    ]
