# Generated by Django 3.1.4 on 2021-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20211008_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='profilePic',
            field=models.ImageField(default='', upload_to='profileImages/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
